### ISSUE TITLE
Error using installdb.php - Loris 20

### ISSUE THREAD

**Issue by bmelo** [aces/Loris#3839]
When I try to create a new database using the address http://[LORIS-URL]/installdb.php I'm having the following errors:

```
[php7:notice] [pid 15] [client 172.18.0.1:34860] Could not execute . Stack trace#0 /var/www/loris/php/installer/Installer.class.inc(216): Database::singleton()\n#1 /var/www/loris/htdocs/installdb.php(107): Installer->sourceSchema(Array)\n#2 {main}, referer: http://localhost/installdb.php
[php7:error] [pid 15] [client 172.18.0.1:34860] PHP Fatal error:  Uncaught DatabaseException: No database connection exists in /var/www/loris/php/libraries/Database.class.inc:104\nStack trace:\n#0 /var/www/loris/php/installer/Installer.class.inc(216): Database::singleton()\n#1 /var/www/loris/htdocs/installdb.php(107): Installer->sourceSchema(Array)\n#2 {main}\n  thrown in /var/www/loris/php/libraries/Database.class.inc on line 104, referer: http://localhost/installdb.php
```

I did the same using version 19 and it worked.

**Comment by johnsaigle** [comment]
@intralizee Is this problem similar to what you addressed recently in https://github.com/aces/Loris/pull/3748? Could you provide any insight here?

**Comment by bmelo** [comment]
Hi, it's working. I was using a version of some days ago , sorry.
Thank you all.
