### ISSUE TITLE
[Imaging Browser] View Session page broken on major for projects not using EDC

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#4184]
The view session page of the imaging browser returns a 500 error for projects not using EDC.

**Error in the apache log:**
`[Thu Dec 06 10:55:33.764466 2018] [php7:error] [pid 32502] [client 132.216.237.95:61312] PHP Fatal error:  Uncaught TypeError: Return value of Candidate::getCandidateEDC() must be of the type string, null returned in /var/www/loris/php/libraries/Candidate.class.inc:493\nStack trace:\n#0 /var/www/loris/modules/imaging_browser/php/viewsession.class.inc(706): Candidate->getCandidateEDC()\n#1 /var/www/loris/modules/imaging_browser/php/viewsession.class.inc(661): LORIS\\imaging_browser\\ViewSession->getSubjectData()\n#2 /var/www/loris/modules/imaging_browser/php/viewsession.class.inc(98): LORIS\\imaging_browser\\ViewSession->getHeaderTable()\n#3 /var/www/loris/php/libraries/NDB_Form.class.inc(188): LORIS\\imaging_browser\\ViewSession->setup()\n#4 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(171): NDB_Form->handle(Object(Zend\\Diactoros\\ServerRequest))\n#5 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(49): LORIS\\Middleware\\UserPageDecorationMiddleware->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\imaging_browser\\ViewSession))\n#6 /var/www/loris/php/libraries/NDB_Page.class.inc(653): LORIS\\M in /var/www/loris/php/libraries/Candidate.class.inc on line 493, referer: https://cecile-dev.loris.ca/imaging_browser/`

**Comment by johnsaigle** [comment]
@cmadjar I think the better solution here is to change the function signature of `getCandidateEDC()` to be nullable, e.g. return `?string` instead of `string`.

This bug was introduced in #4047. In adding return types to all of the function signatures I allowed `null` whenever my VM or Travis would fail. This one happened to sneak through. If this setting is likely to be null in some cases the function should allow it.
