### ISSUE TITLE
[statistics]  Imaging Statistics not working

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4545]
[TestPlan](https://github.com/aces/Loris/blob/minor/modules/statistics/test/TestPlan.md) 
`2. Try clicking on all the tabs. Do they appear to be working?`

Problem:
Click one `Imaging Statistics` tab, nothing happens.

**Comment by johnsaigle** [comment]
Could you include the output of your error log?

My suspicion is that the server you're testing on is missing some configuration settings

**Comment by ridz1208** [comment]
```[Mon May 13 15:08:09.758368 2019] [php7:error] [pid 17239] [client 70.81.209.39:55182] PHP Fatal error:  Uncaught DatabaseException: Unknown column 'DTI_Scan_Done' in 'field list' in /var/www/loris/php/libraries/Database.class.inc:707\nStack trace:\n#0 /var/www/loris/php/libraries/Database.class.inc(739): Database->execute(Object(PDOStatement), Array)\n#1 /var/www/loris/modules/statistics/php/stats_mri.class.inc(384): Database->pselect('SELECT s.Subpro...', Array)\n#2 /var/www/loris/php/libraries/NDB_Form.class.inc(188): LORIS\\statistics\\Stats_MRI->setup()\n#3 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(171): NDB_Form->handle(Object(Zend\\Diactoros\\ServerRequest))\n#4 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(49): LORIS\\Middleware\\UserPageDecorationMiddleware->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Stats_MRI))\n#5 /var/www/loris/php/libraries/NDB_Page.class.inc(653): LORIS\\Middleware\\PageDecorationMiddleware->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Stats_MRI))\n#6 /var/www/loris/php/libraries/Module.class.inc(341): NDB_Page-> in /var/www/loris/php/libraries/Database.class.inc on line 707, referer: https://test.loris.ca/statistics/
```

**Comment by ridz1208** [comment]
the mri_parameter_form does not contain all the necessary columns for each scan_type

**Comment by jftunteng** [comment]
@ridz1208  closing this since the PR is merged.
