### ISSUE TITLE
[statistics] link does not work under behavioural statistics tab

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4555]
[TestPlan](https://github.com/aces/Loris/blob/minor/modules/statistics/test/TestPlan.md#behavioural-statistics) 
`6. Returning to the behavioural statistics page, check that the "Click here for breakdown per participant" link below the Data Entry Statistics table works.`
`11. Returning to the behavioral statistics tab, check that the "Click here for breakdown per participant for" link below the Double Data Entry Statistics table works.`

Problem:
"Click here for breakdown per participant" link does not work for both tables.

**Comment by johnsaigle** [comment]
@ridz1208 Any chance you can post a stack trace here?

**Comment by ridz1208** [comment]
```
[Tue May 14 15:52:03.562359 2019] [php7:error] [pid 28062] [client 132.216.56.93:34880] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to User::hasCenterPermission() must be of the type integer, string given, called in /var/www/loris/modules/statistics/php/statistics_site.class.inc on line 47 and defined in /var/www/loris/php/libraries/User.class.inc:623\nStack trace:\n#0 /var/www/loris/modules/statistics/php/statistics_site.class.inc(47): User->hasCenterPermission('data_entry', '')\n#1 /var/www/loris/php/libraries/Module.class.inc(280): LORIS\\statistics\\Statistics_Site->_hasAccess(Object(User))\n#2 /var/www/loris/src/Middleware/ResponseGenerator.php(49): Module->handle(Object(Zend\\Diactoros\\ServerRequest))\n#3 /var/www/loris/src/Middleware/AuthMiddleware.php(62): LORIS\\Middleware\\ResponseGenerator->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Module))\n#4 /var/www/loris/src/Router/ModuleRouter.php(97): LORIS\\Middleware\\AuthMiddleware->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Module))\n#5 /var/www/loris/src/Router/BaseRouter.php(99): LORIS\\Router\\ModuleRoute in /var/www/loris/php/libraries/User.class.inc on line 623, referer: https://test.loris.ca/statistics/

```

**Comment by johnsaigle** [comment]
This is addressed in the above PR

**Comment by zaliqarosli** [comment]
PR merged
