### ISSUE TITLE
Improve error message when mri_parameter_form doens't exist

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5325]
From loris-dev mailing list

> I can't load the page for quality_control. I get the following error in the loris-error.log, but in short the problem is "Table 'LORIS.mri_parameter_form doesn' exist"
![image](https://user-images.githubusercontent.com/4022790/66944355-029ae680-f01b-11e9-9470-8b09553bdbce.png)

The error message displayed here should say something more helpful along the lines of "The MRI parameter form instrument must be installed in order to use this module."

**Comment by christinerogers** [comment]
This is a snafu for the release, no?  
A slightly more elegant error message would go a long way for the release of this new module. 
Flagging this `Add to Release notes` though it's an Issue and not pegged to 22.  
Also should definitely be added to the Imaging_QC readme #5634

**Comment by racostas** [comment]
This issue was observed again during 25 testing.

**Comment by racostas** [comment]
It prevents the module to load.

**Comment by racostas** [comment]
This is the error log in the backend of Zaliqa VM:
`[Thu Jun 08 10:48:27.306710 2023] [php:notice] [pid 763038] [client 192.168.122.1:36764] [ERROR] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') as tmp GROUP BY PSCID,\n            SessionID,\n            cand_id,\n        ...' at line 1#0 /var/www/loris/php/libraries/Database.class.inc(695): PDOStatement->execute()\n#1 /var/www/loris/php/libraries/Database.class.inc(745): Database->execute()\n#2 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(804): Database->pselect()\n#3 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(745): NDB_Menu_Filter->_getFullList()\n#4 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(774): NDB_Menu_Filter->toArray()\n#5 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(644): NDB_Menu_Filter->toJSON()\n#6 /var/www/loris/php/libraries/NDB_Page.class.inc(743): NDB_Menu_Filter->display()\n#7 /var/www/loris/php/libraries/NDB_Page.class.inc(720): NDB_Page->handle()\n#8 /var/www/loris/php/libraries/Module.class.inc(328): NDB_Page->process()\n#9 /var/www/loris/src/Middleware/ResponseGenerator.php(50): Module->handle()\n#10 /var/www/loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()\n#11 /var/www/loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()\n#12 /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php(54): LORIS\\Router\\ModuleRouter->handle()\n#13 /var/www/loris/src/Router/BaseRouter.php(132): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#14 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#15 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#16 /var/www/loris/htdocs/index.php(55): LORIS\\Middleware\\ContentLength->process()\n#17 {main}, referer: https://copn-stg.loris.ca/imaging_qc/`

**Comment by skarya22** [comment]
Solved by #8779
