### ISSUE TITLE
[Candidate parameters] Cannot save consent to study status

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#5801]
On the test VM, I accessed a candidate for which consent information was never provided. I select 'Yes' to consent to the Study and enter a valid date. When I click `Update`, I get an error popup that says `Update failed`. I see in the server's error log a coding bug:

```
[Wed Nov 27 14:01:18.748132 2019] [php7:error] [pid 24309] [client 192.168.122.1:33176] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Candidate::singleton() must be an instance of LORIS\\StudyEntities\\Candidate\\CandID, string given, called in /var/www/Loris/modules/candidate_parameters/ajax/formHandler.php on line 401 and defined in /var/www/Loris/php/libraries/Candidate.class.inc:52\nStack trace:\n#0 /var/www/Loris/modules/candidate_parameters/ajax/formHandler.php(401): Candidate::singleton('300001')\n#1 /var/www/Loris/modules/candidate_parameters/ajax/formHandler.php(52): editConsentStatusFields(Object(Database), Object(User))\n#2 /var/www/Loris/htdocs/AjaxHelper.php(111): require('/var/www/Loris/...')\n#3 {main}\n  thrown in /var/www/Loris/php/libraries/Candidate.class.inc on line 52, referer: https://test-loris-dev.loris.ca/candidate_parameters/?candID=300001&identifier=300001
```

**Comment by nicolasbrossard** [comment]
Fixed by #5802
