### ISSUE TITLE
ReadTheDocs build failure on LORIS API symlinks

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6209]
**Describe the bug**
ReadTheDocs is failing because it's unable to resolve the following symlinks:

docs/wiki/99\ -\ Developers/LORIS-REST-API-0.0.2.md
docs/wiki/99\ -\ Developers/LORIS-REST-API-0.0.3-dev.md

These were added in https://github.com/aces/Loris/pull/6151

**What did you expect to happen?**
ReadTheDocs and mkdocs should resolve the symlinks and render the documentation.

We may need to modify these to include relative path characters as RTD is served from `docs/` rather than the LORIS root. 

**Additional context**
ReadTheDocs build error:

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/acesloris/checkouts/latest/_build/html 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - React.README.md
  - SQLModelingStandard.md
  - deprecated_wiki/About-superuser.md
  - deprecated_wiki/CentOS-Imaging-installation-transcript.md
  - deprecated_wiki/Code-Customization.md
  - deprecated_wiki/Developer's-Instrument-Guide.md
  - deprecated_wiki/Getting-the-Release.md
  - deprecated_wiki/Guide-to-Loris-React-components.md
  - deprecated_wiki/How-to-Code-an-Instrument.md
  - deprecated_wiki/How-to-make-a-LORIS-module.md
  - deprecated_wiki/Installing-Loris-in-Brief.md
  - deprecated_wiki/Instrument-Groups.md
  - deprecated_wiki/Instrument-Insertion.md
  - deprecated_wiki/Instrument-Scoring.md
  - deprecated_wiki/Instrument-Scripts.md
  - deprecated_wiki/Instrument-Testing-and-Troubleshooting.md
  - deprecated_wiki/LORIS-Dictionary.md
  - deprecated_wiki/LORIS-Form.md
  - deprecated_wiki/LORIS-Module-Testing.md
  - deprecated_wiki/LORIS-Modules.md
  - deprecated_wiki/LORIS-scripts-in-the-tools--directory.md
  - deprecated_wiki/Notification-system.md
  - deprecated_wiki/Open-LORIS.md
  - deprecated_wiki/Other-Imaging-Scripts.md
  - deprecated_wiki/Reloading-MRI-data-for-mislabelled-session.md
  - deprecated_wiki/Updating-your-LORIS.md
  - deprecated_wiki/Upgrading-Loris.md
  - deprecated_wiki/Using-Google-reCAPTCHA.md
  - deprecated_wiki/Working-with-React.md
  - deprecated_wiki/XIN-Rules.md
  - deprecated_wiki/About/About.md
  - deprecated_wiki/Setup/Setup.md
  - deprecated_wiki/Setup/Initial Setup/Backups/Backups.md
  - deprecated_wiki/Setup/Initial Setup/Behavioural Database/Behavioural-Database.md
  - deprecated_wiki/Setup/Initial Setup/Data Querying Tool/Data-Querying-Tool.md
  - deprecated_wiki/Setup/Initial Setup/Enable Mail Server/Enable-mail-server.md
  - deprecated_wiki/Setup/Initial Setup/Imaging Database/Imaging-Database.md
  - deprecated_wiki/Setup/Initial Setup/Install Script/Install-Script.md
  - deprecated_wiki/Setup/Initial Setup/LORIS Modules/Candidate Information Page/Candidate-Information-Page.md
  - deprecated_wiki/Setup/Initial Setup/LORIS Modules/Candidate Parameters/Candidate-Parameters.md
  - deprecated_wiki/Technical/Code-Review-Checklist.md
  - deprecated_wiki/Technical/Developer-Workshop-2015-02-13.md
  - deprecated_wiki/Technical/Developer-Workshops.md
  - deprecated_wiki/Technical/Technical.md
  - wiki/00 - SERVER INSTALL AND CONFIGURATION/README.md
  - wiki/00 - SERVER INSTALL AND CONFIGURATION/01 - LORIS Install/README.md
  - wiki/00 - SERVER INSTALL AND CONFIGURATION/01 - LORIS Install/Macintosh/README.md
  - wiki/01 - STUDY PARAMETERS SETUP/README.md
  - wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/README.md
  - wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/01 - Identifiers.md
  - wiki/_ARCHIVE/README.md
  - wiki/_DELETED/README.md
  - wiki/_DELETED/API.md
  - wiki/_DELETED/Install-Script-for-16.X.md
  - wiki/_DELETED/Installing-Loris-(After-Installing-Prerequisites).md
  - wiki/_DELETED/LORIS database schema.md
  - wiki/_DELETED/LORIS-Setup-Schematic.md
  - wiki/_DELETED/Request-Accounts-module.md
  - wiki/_DELETED/_Footer.md
  - wiki/_DELETED/_Sidebar.md
  - wiki/_DELETED/Community/Community.md
  - wiki/_DELETED/Community/Development.md
  - wiki/_DELETED/Community/Documentation.md
  - wiki/_DELETED/Community/Get-in-Touch.md
  - wiki/_DELETED/Resources/Instrument Coding Guide/Instrument-Coding-Guide.md
  - wiki/_DELETED/Resources/Ubuntu Upgrading/Upgrading-from-Ubuntu-12.04-to-14.04.md 
WARNING -  Documentation file 'CodingStandards.md' contains a link to 'wiki/99%20-%20Developers/Automated%20Testing.md' which is not found in the documentation files. 
WARNING -  Documentation file 'deprecated_wiki/Setup/Initial Setup/Install Script/Install-Script.md' contains a link to 'deprecated_wiki/Setup/Initial Setup/Install Script/Install-Script-for-16.X' which is not found in the documentation files. 
WARNING -  Documentation file 'wiki/00 - SERVER INSTALL AND CONFIGURATION/01 - LORIS Install/CentOS/README.md' contains a link to '../README.md' which is not found in the documentation files. 
WARNING -  Documentation file 'wiki/00 - SERVER INSTALL AND CONFIGURATION/01 - LORIS Install/CentOS/README.md' contains a link to '../README.md' which is not found in the documentation files. 
WARNING -  Documentation file 'wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/03 - Sites.md' contains a link to 'wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/SQL Dictionary.md' which is not found in the documentation files. 
WARNING -  Documentation file 'wiki/99 - Developers/Automated Testing.md' contains a link to '../test/UnitTestGuide.md' which is not found in the documentation files. 
ERROR   -  File not found: wiki/99 - Developers/LORIS-REST-API-0.0.2.md 
ERROR   -  Error reading page 'wiki/99 - Developers/LORIS-REST-API-0.0.2.md': [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/acesloris/checkouts/latest/docs/wiki/99 - Developers/LORIS-REST-API-0.0.2.md' 
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/__main__.py", line 202, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/commands/build.py", line 170, in _populate_page
    page.read_source(config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/structure/pages.py", line 129, in read_source
    with io.open(self.file.abs_src_path, 'r', encoding='utf-8-sig', errors='strict') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/acesloris/checkouts/latest/docs/wiki/99 - Developers/LORIS-REST-API-0.0.2.md'
```

**Comment by christinerogers** [comment]
cc @AlexandraLivadas @laemtl  for examples of symlinks in the docs

**Comment by johnsaigle** [comment]
>  examples of symlinks in the docs

specifically that they don't work!
