### ISSUE TITLE
[Document Repository] Download issue

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6304]
Test plan: 6 

After uploading a file from a user account, I cannot download it from admin but admin can download it without problems. Same issue vice versa.

**Comment by ridz1208** [comment]
>  I cannot download it from admin but admin can download it without problems

Not sure i understand this sentence

**Comment by pierre-p-s** [comment]
> > I cannot download it from admin but admin can download it without problems
> 
> Not sure i understand this sentence

My issue is: if admin uploads a file, then admin can retrieve this file downloading it from Loris. However if another user tries to download it, it gives an error.

**Comment by kongtiaowang** [comment]
This is a major bug in this module. Even admin user can only download his own files.

**Comment by HenriRabalais** [comment]
I'm trying to test but getting this error. Do i have to manually make a director for each user?
```
[Thu Apr 30 14:42:36.747292 2020] [php7:warn] [pid 25091] [client 10.31.11.193:54259] PHP Warning:  mkdir(): No such file or directory in /var/www/loris/modules/document_repository/php/files.class.inc on line 370, referer: http://hrabalais-dev.loris.ca/document_repository/
[Thu Apr 30 14:42:36.747500 2020] [php7:error] [pid 25091] [client 10.31.11.193:54259] PHP Fatal error:  Uncaught LorisException: Cannot create directory /data/document_repository_uploads/admin/. in /var/www/loris/modules/document_repository/php/files.class.inc:371\nStack trace:\n#0 /var/www/loris/modules/document_repository/php/files.class.inc(76): LORIS\\document_repository\\Files->uploadDocFile(Object(Laminas\\Diactoros\\ServerRequest))\n#1 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(234): LORIS\\document_repository\\Files->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#2 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(56): LORIS\\Middleware\\UserPageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\document_repository\\Files))\n#3 /var/www/loris/php/libraries/NDB_Page.class.inc(701): LORIS\\Middleware\\PageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\document_repository\\Files))\n#4 /var/www/loris/php/libraries/Module.class.inc(412): NDB_Page->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\document_reposito in /var/www/loris/modules/document_repository/php/files.class.inc on line 371, referer: http://hrabalais-dev.loris.ca/document_repository/
```
