### ISSUE TITLE
[user_accounts] expects parameter 2 to be string, null given 

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#6343]
**Describe the bug**
Visiting user_accounts on clean install of LORIS will return this error output in error_log:
```
PHP TypeError:  explode() expects parameter 2 to be string, null given in /Users/alizee/Development/GitHub/McGill/Loris/modules/user_accounts/php/useraccountrowprovisioner.class.inc on line 48, referer: http://localhost/user_accounts/
PHP Stack trace:, referer: http://localhost/user_accounts/
[Wed Apr 08 16:11:31.044636 2020] [php7:notice] [pid 36180] [client ::1:59838] PHP   1. {main}() /Users/alizee/Development/GitHub/McGill/Loris/htdocs/index.php:0, referer: http://localhost/user_accounts/
PHP   2. LORIS\\Middleware\\ContentLength->process() /Users/alizee/Development/GitHub/McGill/Loris/htdocs/index.php:47, referer: http://localhost/user_accounts/
PHP   3. LORIS\\Middleware\\ResponseGenerator->process() /Users/alizee/Development/GitHub/McGill/Loris/src/Middleware/ContentLength.php:52, referer: http://localhost/user_accounts/
PHP   4. LORIS\\Router\\BaseRouter->handle() /Users/alizee/Development/GitHub/McGill/Loris/src/Middleware/ResponseGenerator.php:50, referer: http://localhost/user_accounts/
PHP   5. LORIS\\Router\\ModuleRouter->handle() /Users/alizee/Development/GitHub/McGill/Loris/src/Router/BaseRouter.php:105, referer: http://localhost/user_accounts/
PHP   6. LORIS\\Middleware\\AuthMiddleware->process() /Users/alizee/Development/GitHub/McGill/Loris/src/Router/ModuleRouter.php:75, referer: http://localhost/user_accounts/
PHP   7. LORIS\\Middleware\\ResponseGenerator->process() /Users/alizee/Development/GitHub/McGill/Loris/src/Middleware/AuthMiddleware.php:63, referer: http://localhost/user_accounts/
PHP   8. LORIS\\user_accounts\\Module->handle() /Users/alizee/Development/GitHub/McGill/Loris/src/Middleware/ResponseGenerator.php:50, referer: http://localhost/user_accounts/
PHP   9. LORIS\\user_accounts\\Module->handle() /Users/alizee/Development/GitHub/McGill/Loris/modules/user_accounts/php/module.class.inc:41, referer: http://localhost/user_accounts/
PHP  10. LORIS\\user_accounts\\User_Accounts->process() /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/Module.class.inc:412, referer: http://localhost/user_accounts/
PHP  11. LORIS\\user_accounts\\User_Accounts->handle() /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Page.class.inc:692, referer: http://localhost/user_accounts/
PHP  12. LORIS\\user_accounts\\User_Accounts->display() /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Page.class.inc:713, referer: http://localhost/user_accounts/
PHP  13. LORIS\\user_accounts\\User_Accounts->toJSON() /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Menu_Filter.class.inc:682, referer: http://localhost/user_accounts/
PHP  14. LORIS\\Data\\Table->toJSON() /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/DataFrameworkMenu.class.inc:139, referer: http://localhost/user_accounts/
PHP  15. LORIS\\Data\\Table->toArray() /Users/alizee/Development/GitHub/McGill/Loris/src/Data/Table.php:98, referer: http://localhost/user_accounts/
PHP  16. CallbackFilterIterator->next() /Users/alizee/Development/GitHub/McGill/Loris/src/Data/Table.php:83, referer: http://localhost/user_accounts/
PHP  17. {anonymous-class:/Users/alizee/Development/GitHub/McGill/Loris/src/Data/Provisioners/DBRowProvisioner.php:95-120}->current() /Users/alizee/Development/GitHub/McGill/Loris/src/Data/Table.php:83, referer: http://localhost/user_accounts/
PHP  18. LORIS\\user_accounts\\UserAccountRowProvisioner->getInstance() /Users/alizee/Development/GitHub/McGill/Loris/src/Data/Provisioners/DBRowProvisioner.php:118, referer: http://localhost/user_accounts/
PHP  19. explode() /Users/alizee/Development/GitHub/McGill/Loris/modules/user_accounts/php/useraccountrowprovisioner.class.inc:48, referer: http://localhost/user_accounts/
PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, null given in /Users/alizee/Development/GitHub/McGill/Loris/modules/user_accounts/php/useraccountrowprovisioner.class.inc:48\nStack trace:\n#0 /Users/alizee/Development/GitHub/McGill/Loris/modules/user_accounts/php/useraccountrowprovisioner.class.inc(48): explode(',', NULL)\n#1 /Users/alizee/Development/GitHub/McGill/Loris/src/Data/Provisioners/DBRowProvisioner.php(118): LORIS\\user_accounts\\UserAccountRowProvisioner->getInstance(Array)\n#2 [internal function]: class@anonymous->current()\n#3 /Users/alizee/Development/GitHub/McGill/Loris/src/Data/Table.php(83): FilterIterator->next()\n#4 /Users/alizee/Development/GitHub/McGill/Loris/src/Data/Table.php(98): LORIS\\Data\\Table->toArray(Object(User))\n#5 /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/DataFrameworkMenu.class.inc(139): LORIS\\Data\\Table->toJSON(Object(User))\n#6 /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Menu_Filter.class.inc(682): DataFrameworkMenu->toJSON()\n#7 / in /Users/alizee/Development/GitHub/McGill/Loris/modules/user_accounts/php/useraccountrowprovisioner.class.inc on line 48, referer: http://localhost/user_accounts/

```

I'm using Rasinbread data and logged-in as admin. It seems like Admin doesn't have any projectIds associated to the account.

**Comment by maltheism** [comment]
Note: I'm using Rasinbread data and logged-in as admin.

**Comment by maltheism** [comment]
Issue seems to be resolved after resourcing rasinbread. So closing.
