### ISSUE TITLE
[API] Project /images endpoint broken

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#6572]
**Describe the bug**
`GET /projects/$ProjectName/images/` returned `{"Images":[]}` and now, returns 500 error.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'https://test-loris-dev.loris.ca/api/v0.0.3/projects/Rye/images'. You get a 500 or empty "Images" array

**What did you expect to happen?**
Non-empty "Images" array with JSON objects of images data

**Comment by ridz1208** [comment]
@spell00 any progress on this one ?

**Comment by spell00** [comment]
similarly to #6570 and #6571, I can replicate the issue on the testing VM, but not my personal dev VM

**Comment by kongtiaowang** [comment]
[Fri May 29 19:03:22.146493 2020] [php7:error] [pid 8194] [client 192.168.122.1:54994] PHP Fatal error:  Uncaught TypeError: basename() expects parameter 1 to be string, null given in /var/www/Loris/modules/api/php/models/projectimagesrow.class.inc:79\nStack trace:\n#0 /var/www/Loris/modules/api/php/models/projectimagesrow.class.inc(79): basename(NULL)\n#1 /var/www/Loris/src/Data/Table.php(84): LORIS\\api\\Models\\ProjectImagesRow->toJSON(Object(User))\n#2 /var/www/Loris/modules/api/php/endpoints/project/images.class.inc(133): LORIS\\Data\\Table->toArray(Object(User))\n#3 /var/www/Loris/modules/api/php/endpoints/project/images.class.inc(88): LORIS\\api\\Endpoints\\Project\\Images->_handleGET(Object(Laminas\\Diactoros\\ServerRequest))\n#4 /var/www/Loris/src/Middleware/ETag.php(74): LORIS\\api\\Endpoints\\Project\\Images->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#5 /var/www/Loris/modules/api/php/endpoint.class.inc(70): LORIS\\Middleware\\ETag->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\api\\Endpoints\\Project\\Images))\n#6 /var/www/Loris/modules/api/php/endpoints/project/project.class.inc(127): LORIS\\Api\\Endpoint-> in /var/www/Loris/modules/api/php/models/projectimagesrow.class.inc on line 79

**Comment by AlexandraLivadas** [comment]
I was able to replicate this both on the testing VM and my own VM (head at 23.0-release) this afternoon.

**Comment by spell00** [comment]
I can replicate it on my own VM too now
