### ISSUE TITLE
RTD Build errors

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#6736]
>ERROR   -  Error reading page 'wiki/99 - Developers/LORIS-REST-API-0.0.2.md': [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/acesloris/checkouts/latest/docs/wiki/99 - Developers/LORIS-REST-API-0.0.2.md' 
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/__main__.py", line 202, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/commands/build.py", line 170, in _populate_page
    page.read_source(config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/acesloris/envs/latest/lib/python3.7/site-packages/mkdocs/structure/pages.py", line 129, in read_source
    with io.open(self.file.abs_src_path, 'r', encoding='utf-8-sig', errors='strict') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/acesloris/checkouts/latest/docs/wiki/99 - Developers/LORIS-REST-API-0.0.2.md'

**Comment by laemtl** [comment]
Fixed in #6667
