### ISSUE TITLE
[Unit tests] - Could not execute errors in /app/test/unittests/Database_Test.php

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6778]
An [error_log](https://github.com/aces/Loris/blob/7f7fe5a8d7581ca84dc2905ee74e89084c06ddee/php/exceptions/DatabaseException.class.inc#L44) in DatabaseException::__construct() causes Travis to prints some `Could not execute [...]` errors when running the tests in /app/test/unittests/Database_Test.php expected to throw exceptions.

This is polluting the output and makes error hunting more difficult.

**Comment by laemtl** [comment]
...Could not execute SELECT ID, Name FROM ConfigSettings. Stack trace#0 /app/test/unittests/Database_Test.php(1184): Database->pselectCol('SELECT ID, Name...', Array)
#1 [internal function]: Database_Test->testPselectColThrowsException()
#2 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1156): ReflectionMethod->invokeArgs(Object(Database_Test), Array)
#3 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(729): PHPUnit\Framework\TestCase->runTest()
#4 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(710): PHPUnit\Framework\TestCase->runBare()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(687): PHPUnit\Framework\TestResult->run(Object(Database_Test))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(508): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#12 /app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#13 {main}


......I..Could not execute SELECT ID, Name FROM ConfigSettings. Stack trace#0 /app/test/unittests/Database_Test.php(1388): Database->pselectWithIndexKey('SELECT ID, Name...', Array, 'Test')
#1 [internal function]: Database_Test->testPselectWithIndexKeyThrowsDbException()
#2 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1156): ReflectionMethod->invokeArgs(Object(Database_Test), Array)
#3 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(729): PHPUnit\Framework\TestCase->runTest()
#4 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(710): PHPUnit\Framework\TestCase->runBare()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(687): PHPUnit\Framework\TestResult->run(Object(Database_Test))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(508): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#12 /app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#13 {main}

...Could not execute SELECT Name FROM ConfigSettings. Stack trace#0 /app/test/unittests/Database_Test.php(1487): Database->pselectColWithIndexKey('SELECT Name FRO...', Array, 'ID')
#1 [internal function]: Database_Test->testPselectColWithIndexKeyThrowsDbExceptionOne()
#2 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1156): ReflectionMethod->invokeArgs(Object(Database_Test), Array)
#3 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(729): PHPUnit\Framework\TestCase->runTest()
#4 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(710): PHPUnit\Framework\TestCase->runBare()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(687): PHPUnit\Framework\TestResult->run(Object(Database_Test))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(508): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#12 /app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#13 {main}
.Could not execute SELECT Visible, Name FROM ConfigSettings. Stack trace#0 /app/test/unittests/Database_Test.php(1519): Database->pselectColWithIndexKey('SELECT Visible,...', Array, 'Visible')
#1 [internal function]: Database_Test->testPselectColWithIndexKeyThrowsDbExceptionTwo()
#2 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1156): ReflectionMethod->invokeArgs(Object(Database_Test), Array)
#3 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(729): PHPUnit\Framework\TestCase->runTest()
#4 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(710): PHPUnit\Framework\TestCase->runBare()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(687): PHPUnit\Framework\TestResult->run(Object(Database_Test))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(508): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#12 /app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#13 {main}
.....Could not execute . Stack trace#0 /app/test/unittests/Database_Test.php(1616): Database->beginTransaction()
#1 [internal function]: Database_Test->testBeginTransactionThrowsException()
#2 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1156): ReflectionMethod->invokeArgs(Object(Database_Test), Array)
#3 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(729): PHPUnit\Framework\TestCase->runTest()
#4 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(710): PHPUnit\Framework\TestCase->runBare()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(687): PHPUnit\Framework\TestResult->run(Object(Database_Test))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(508): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#12 /app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#13 {main}
..Could not execute . Stack trace#0 /app/test/unittests/Database_Test.php(1654): Database->rollBack()
#1 [internal function]: Database_Test->testRollbackThrowsException()
#2 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1156): ReflectionMethod->invokeArgs(Object(Database_Test), Array)
#3 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(729): PHPUnit\Framework\TestCase->runTest()
#4 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(710): PHPUnit\Framework\TestCase->runBare()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(687): PHPUnit\Framework\TestResult->run(Object(Database_Test))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(508): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#12 /app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#13 {main}
..Could not execute . Stack trace#0 /app/test/unittests/Database_Test.php(1692): Database->commit()
#1 [internal function]: Database_Test->testCommitThrowsException()
#2 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1156): ReflectionMethod->invokeArgs(Object(Database_Test), Array)
#3 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(729): PHPUnit\Framework\TestCase->runTest()
#4 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(710): PHPUnit\Framework\TestCase->runBare()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(687): PHPUnit\Framework\TestResult->run(Object(Database_Test))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(508): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#12 /app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#13 {main}

**Comment by laemtl** [comment]
Seems to be related to #6553

**Comment by laemtl** [comment]
Fixed
