### ISSUE TITLE
SQL Errors in Travis unit tests

### ISSUE THREAD

**Issue by driusan** [aces/Loris#7013]
The errors log in Travis contains numerous errors of the form:

```
Could not execute SELECT ID, Name FROM ConfigSettings. Stack trace#0 /app/test/unittests/Database_Test.php(1427): Database->pselectWithIndexKey('SELECT ID, Name...', Array, 'Test')

#1 [internal function]: Database_Test->testPselectWithIndexKeyThrowsDbException()
#2 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1156): ReflectionMethod->invokeArgs(Object(Database_Test), Array)
#3 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(729): PHPUnit\Framework\TestCase->runTest()
#4 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(710): PHPUnit\Framework\TestCase->runBare()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(687): PHPUnit\Framework\TestResult->run(Object(Database_Test))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(508): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#12 /app/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#13 {main}
```

on the main branch. The tests still pass regardless of the SQL, but the errors shouldn't be happening (and, in fact, I don't see why Travis is passing the tests if it's throwing an exception..)

For instance, see the `TEST_SUITE=unit` logs in the latest Travis run on the main branch: https://travis-ci.org/github/aces/Loris/jobs/724264534

**Comment by laemtl** [comment]
Realted to #6778. Those are assert created by #6553

**Comment by driusan** [comment]
Thanks @laemtl.. closing this because it seems to be a duplicate of #6778
