### ISSUE TITLE
[23.0][battery_manager] Issue with test battery assignnment for duplicate tests

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7130]
**Describe the bug**
If you add the same instrument to a timepoint (changing the min/max dates or another parameter, but keeping test and timepoint the same), you get duplicated entries in the instrument list. For example, in the screenshot below. Test was added twice, but appears 4 times in the instrument list. Duplicated commentIDs.

![image](https://user-images.githubusercontent.com/34260251/99570019-5951bd00-299f-11eb-8fcb-9482c92a8015.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `Battery Manager`
2. Add a test.
3. Add the same test again to the same timepoint with a different max age.
4. Start a new visit for that timepoint and observe the error in the test battery.

**What did you expect to happen?**
No duplication.

**Additional notes**
Not even sure we want to be able to add the same test to the timepoint anyways regardless of the age min/max being different ? Should this simply be flagged as attempting to add the same instrument to the battery and thus not processed?

**Comment by ridz1208** [comment]
@jesscall could you attach a screeshot of the database in MySQL ?

**Comment by jesscall** [comment]
<img width="1154" alt="Screen Shot 2020-11-19 at 12 24 01 PM" src="https://user-images.githubusercontent.com/34260251/99701189-1f95ba80-2a62-11eb-9562-de2d416be13b.png">

**Comment by ridz1208** [comment]
@jesscall let me know if/when ur able to reproduce

**Comment by jesscall** [comment]
Not able to reproduce quadruplication, but I get another error...

EX test_battery:
```
+------+---------------+------------+------------+--------+-------+--------------+------------------------------+----------+------------+-------------+
| ID   | Test_name     | AgeMinDays | AgeMaxDays | Active | Stage | SubprojectID | Visit_label                  | CenterID | firstVisit | instr_order |
+------+---------------+------------+------------+--------+-------+--------------+------------------------------+----------+------------+-------------+
|  320 | Screening_SCI |          0 | 2147483647 | Y      | Visit |            1 | Initial_Assessment_Screening |     NULL | NULL       |          26 |
| 6917 | Screening_SCI |          1 |   20000000 | Y      | Visit |            1 | Initial_Assessment_Screening |     NULL | NULL       |        NULL |
+------+---------------+------------+------------+--------+-------+--------------+------------------------------+----------+------------+-------------+
```

When I start visit stage:
```
[Wed Dec 16 12:52:34.844752 2020] [php7:notice] [pid 21923] [client 192.168.122.1:48418] Could not execute INSERT INTO Screening_SCI SET `CommentID`=:CommentID. Stack trace#0 /var/www/ccna/php/libraries/Database.class.inc(251): Database->_realinsert('Screening_SCI', Array, true)\n#1 /var/www/ccna/php/libraries/NDB_BVL_Battery.class.inc(200): Database->insert('Screening_SCI', Array)\n#2 /var/www/ccna/php/libraries/NDB_BVL_Battery.class.inc(158): NDB_BVL_Battery->addInstrument('Screening_SCI')\n#3 /var/www/ccna/modules/next_stage/php/next_stage.class.inc(124): NDB_BVL_Battery->createBattery(1, 'Visit', 'Initial_Assessm...', 34, true)\n#4 /var/www/ccna/php/libraries/NDB_Form.class.inc(157): LORIS\\next_stage\\Next_Stage->_process(Array)\n#5 /var/www/ccna/php/libraries/LorisForm.class.inc(1432): NDB_Form->_save(Array)\n#6 /var/www/ccna/php/libraries/NDB_Form.class.inc(128): LorisForm->process(Array)\n#7 /var/www/ccna/php/libraries/NDB_Form.class.inc(187): NDB_Form->save()\n#8 /var/www/ccna/src/Middleware/UserPageDecorationMiddleware.php(234): NDB_Form->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#9 /var/www/ccna/src/Middleware/PageDecorationMiddleware.php(56): LORIS\\Middleware\\UserPageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\next_stage\\Next_Stage))\n#10 /var/www/ccna/php/libraries/NDB_Page.class.inc(692): LORIS\\Middleware\\PageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\next_stage\\Next_Stage))\n#11 /var/www/ccna/php/libraries/Module.class.inc(412): NDB_Page->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\next_stage\\Next_Stage))\n#12 /var/www/ccna/src/Middleware/ResponseGenerator.php(50): Module->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#13 /var/www/ccna/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\next_stage\\Module))\n#14 /var/www/ccna/src/Router/ModuleRouter.php(75): LORIS\\Middleware\\AuthMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\next_stage\\Module))\n#15 /var/www/ccna/src/Router/BaseRouter.php(105): LORIS\\Router\\ModuleRouter->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#16 /var/www/ccna/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#17 /var/www/ccna/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#18 /var/www/ccna/htdocs/index.php(47): LORIS\\Middleware\\ContentLength->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#19 {main}, referer: https://ccna-dev.loris.ca/next_stage/?candID=803827&sessionID=7602&identifier=7602
[Wed Dec 16 12:52:34.844993 2020] [php7:error] [pid 21923] [client 192.168.122.1:48418] PHP Fatal error:  Uncaught DatabaseException: Insert statement did not execute successfully: SQLSTATE: . ERROR CODE: . ERROR MESSAGE:  in /var/www/ccna/php/libraries/Database.class.inc:418\nStack trace:\n#0 /var/www/ccna/php/libraries/Database.class.inc(251): Database->_realinsert('Screening_SCI', Array, true)\n#1 /var/www/ccna/php/libraries/NDB_BVL_Battery.class.inc(200): Database->insert('Screening_SCI', Array)\n#2 /var/www/ccna/php/libraries/NDB_BVL_Battery.class.inc(158): NDB_BVL_Battery->addInstrument('Screening_SCI')\n#3 /var/www/ccna/modules/next_stage/php/next_stage.class.inc(124): NDB_BVL_Battery->createBattery(1, 'Visit', 'Initial_Assessm...', 34, true)\n#4 /var/www/ccna/php/libraries/NDB_Form.class.inc(157): LORIS\\next_stage\\Next_Stage->_process(Array)\n#5 /var/www/ccna/php/libraries/LorisForm.class.inc(1432): NDB_Form->_save(Array)\n#6 /var/www/ccna/php/libraries/NDB_Form.class.inc(128): LorisForm->process(Array)\n#7 /var/www/ccna/php/libraries/NDB_Form.class.inc(187): NDB_Form->save()\n#8 /var/www/ccna/src/Middleware/UserPa in /var/www/ccna/php/libraries/Database.class.inc on line 418, referer: https://ccna-dev.loris.ca/next_stage/?candID=803827&sessionID=7602&identifier=7602
```

Ultimately not a bug with battery manager.

**Comment by ridz1208** [comment]
This is an edge case error that happens when the project uses instrument ordering in the battery AND has redundant rows in the test_battery (2 rows matching the lookupbattery)

The solution to the issue is to use a group by in the instrument_list query (instead of the current DISTINCT). I have a PR going to main with a complete deletion of the battery lookup function for instrument list. I could include the fix there or make a fix for 23 and push it there...

reference PR https://github.com/aces/Loris/pull/7167

**Comment by ridz1208** [comment]
@jesscall could you check if this still happens after #7167 was merged ?

**Comment by driusan** [comment]
@jesscall can you respond to @ridz1208's question?

**Comment by jesscall** [comment]
Yes, sorry. I forgot to update the ticket but had a message exchange with Rida back in Nov about this. 

There is still an issue, but not the duplication of tests.

**_Test case_**: `the project uses instrument ordering in the battery AND has redundant rows in the test_battery (2 rows matching the lookupbattery)`

<img width="1303" alt="Screen Shot 2021-12-14 at 10 33 10 AM" src="https://user-images.githubusercontent.com/34260251/146028974-4254e510-9941-4031-a7e3-aca67d3a9382.png">


**_Test Environment_**: test-loris-dev VM

**_Result_**: `Something went wrong`

<img width="1153" alt="Screen Shot 2021-12-14 at 10 32 59 AM" src="https://user-images.githubusercontent.com/34260251/146029045-3eb35326-76ed-44ae-8d55-7b77ddc54f05.png">

From my chat log with @ridz1208, I got this error on a different VM:
```
PHP Warning:  PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '375216DCC5482162261636479963' for key 'PRIMARY' in /var/www/loris/php/libraries/Database.class.inc on line 437, referer: http://localhost:8080/next_stage/?candID=375216&sessionID=2162&identifier=2162
[Tue Nov 09 12:46:03.903501 2021] [php7:notice] [pid 24398] [client ::1:60374] Could not execute INSERT INTO aosi SET `CommentID`=:CommentID. Stack trace#0 
```

I can't be sure however if it's the same error thrown on test VM. Can someone who has access check the logs?
