### ISSUE TITLE
getScreeningStatus() return type issue

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#7282]
getScreeningStatus() return type does not allow null value, but Screening, in the session table, can be null (a quick look at the session table can convince you). When it is, calling getScreeningStatus() triggers a fatal error:

```
php fix_timepoint_date_problems.php diagnose 587630
Candidate: 587630 
 Timepoint V1 ; SubProjectID: 1 ; Effective DOB: 2016-05-01 ; (SessionID): 1053 
PHP Fatal error:  Uncaught TypeError: Return value of TimePoint::getScreeningStatus() must be of the type string, null returned in /var/www/html/loris-core/php/libraries/TimePoint.class.inc:491
Stack trace:
#0 /var/www/html/loris-core/tools/fix_timepoint_date_problems.php(661): TimePoint->getScreeningStatus()
#1 /var/www/html/loris-core/tools/fix_timepoint_date_problems.php(286): diagnose()
#2 {main}
  thrown in /var/www/html/loris-core/php/libraries/TimePoint.class.inc on line 491
```

The return type should either allow null values, or the function should return an empty string instead of null values.

**Comment by laemtl** [comment]
@driusan Any thoughts?
