### ISSUE TITLE
Error with Make: make: *** [Makefile:15: javascript] Error 2

### ISSUE THREAD

**Issue by kefsaj** [aces/Loris#8170]

**Comment by cmadjar** [comment]
@kefsaj I transferred the issue to the LORIS repo as the issue you are having is happening on the LORIS JS side and not with the LORIS-MRI scripts.

I am unsure what the issue might be. @laemtl @driusan @kongtiaowang any idea?

**Comment by kefsaj** [comment]
Thank you!
Happy to provide more info as needed.

**Comment by kefsaj** [comment]
Hi Folks,
Just checking if anyone could help us on this front.
Thanks!

**Comment by laemtl** [comment]
Hello @kefsaj, which release version are you using?

**Comment by kefsaj** [comment]
> Hello @kefsaj, which release version are you using?

@laemtl Hey thank you for the reply!
Using the latest version of LORIS, 24.0.3

**Comment by laemtl** [comment]
Can you try to update [package.json](https://github.com/kongtiaowang/Loris/blob/24.0-release/package.json) with the following content:

`{
  "name": "loris",
  "version": "1.0.0",
  "description": "Note that the README in LORIS assumes that LORIS is being run on Ubuntu.",
  "directories": {
    "doc": "docs",
    "test": "test"
  },
  "dependencies": {
    "@babel/plugin-transform-runtime": "^7.10.5",
    "@babel/runtime": "^7.10.5",
    "@fortawesome/fontawesome-free": "^5.11.2",
    "copy-webpack-plugin": "^6.2.1",
    "jstat": "^1.9.5",
    "papaparse": "^5.3.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.38",
    "react-addons-create-fragment": "^15.6.2",
    "react-dom": "^17.0.1",
    "react-markdown": "^5.0.2",
    "style-loader": "^1.1.3",
    "swagger-ui-dist": "^3.47.1",
    "sweetalert2": "^8.18.6"
  },
  "devDependencies": {
    "@babel/cli": "^7.6.4",
    "@babel/core": "^7.11.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.6.2",
    "@babel/preset-env": "^7.9.6",
    "@babel/preset-react": "^7.6.3",
    "@types/react": "^17.0.38",
    "@types/react-dom": "^16.9.9",
    "@types/react-redux": "7.1.16",
    "alex": ">=8.0.1",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "c3": "^0.7.15",
    "css-loader": "^3.4.2",
    "d3": "^5.15.0",
    "eslint": "^7.17.0",
    "eslint-config-google": "0.9.1",
    "eslint-plugin-no-jquery": "^2.6.0",
    "eslint-plugin-react": "^7.16.0",
    "eslint-webpack-plugin": "2.1.0",
    "null-loader": "^4.0.1",
    "style-loader": "^1.1.3",
    "terser-webpack-plugin": "^1.3.0",
    "ts-loader": "^8.3.0",
    "typescript": "^3.0.1",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.0"
  },
  "resolutions": {
    "@types/react": "^17.0.38"
  },
  "scripts": {
    "lint:javascript": "./test/run-js-linter.sh",
    "lintfix:javascript": "eslint --fix --ext .js, jsx modules",
    "lint:php": "./test/run-php-linter.sh",
    "lintfix:php": "./test/run-php-linter.sh -f",
    "tests:static": "make checkstatic",
    "lint:shell": "./test/run-shell-linter.sh",
    "tests:unit": "./test/dockerized-unit-tests.sh",
    "tests:unit:debug": "DEBUG=true ./test/dockerized-unit-tests.sh",
    "tests:integration": "./test/dockerized-integration-tests.sh",
    "tests:integration:debug": "DEBUG=true ./test/dockerized-integration-tests.sh",
    "compile": "webpack",
    "watch": "webpack --watch",
    "postinstall": "cd modules/electrophysiology_browser/jsx/react-series-data-viewer && npm install"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/aces/Loris.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/aces/Loris/issues"
  },
  "homepage": "https://github.com/aces/Loris"
}
`

**Comment by kefsaj** [comment]
@laemtl Thank you for the reply! I updated both JSON files but I am still getting the same errors.

`    ERROR in /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx
    ./modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx 98:11-15
    [tsl] ERROR in /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx(98,12)
          TS2786: 'Rail' cannot be used as a JSX component.
      Its instance type 'Rail' is not a valid JSX element.
        The types returned by 'render()' are incompatible between these types.
          Type 'string | number | boolean | {} | Iterable<ReactNode> | ReactPortal | ReactElement<any, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<...>)>' is not assignable to type 'ReactNode'.
            Type '{}' is not assignable to type 'ReactNode'.
              Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props
    
    ERROR in /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx
    ./modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx 103:11-18
    [tsl] ERROR in /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx(103,12)
          TS2786: 'Handles' cannot be used as a JSX component.
      Its instance type 'Handles' is not a valid JSX element.
        The types returned by 'render()' are incompatible between these types.
          Type 'string | number | boolean | {} | Iterable<ReactNode> | ReactPortal | ReactElement<any, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<...>)>' is not assignable to type 'ReactNode'.
            Type '{}' is not assignable to type 'ReactNode'.
              Type '{}' is not assignable to type 'ReactPortal'.
    
    ERROR in /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx
    ./modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx 117:11-16
    [tsl] ERROR in /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx(117,12)
          TS2786: 'Ticks' cannot be used as a JSX component.
      Its instance type 'Ticks' is not a valid JSX element.
        The types returned by 'render()' are incompatible between these types.
          Type 'ReactElement<any, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<any, any, any>)>' is not assignable to type 'ReactNode'.
            Property 'children' is missing in type 'ReactElement<any, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<any, any, any>)>' but required in type 'ReactPortal'.
    
    ERROR in /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx
    ./modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx 165:7-15
    [tsl] ERROR in /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx(165,8)
          TS2786: 'Provider' cannot be used as a JSX component.
      Its instance type 'Provider<AnyAction>' is not a valid JSX element.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/node_modules/@visx/group/node_modules/@types/react/index").ReactNode'.
            Type '{}' is not assignable to type 'ReactNode'.
              Type '{}' is not assignable to type 'ReactPortal'.
make: *** [Makefile:15: javascript] Error 2

`

**Comment by laemtl** [comment]
Can you try again? I updated my previous answer. 
Make sure to remove the node_modules before:
```
rm -r /var/www/loris/node_modules/
rm -r /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/node_modules/
```

**Comment by kefsaj** [comment]
@laemtl Just an update, I did the remove commands and updated the JSON packages. 
This is the result. 

Also tried ``` npm cache clean --force ``` 

Output in terminal: 
```
lorisadmin@ubuntu-focal:/var/www/loris$ make
tools/gen-version.sh
npm install 
npm ERR! Invalid Version: ^7.1.16

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lorisadmin/.npm/_logs/2022-09-28T15_06_53_305Z-debug-0.log
make: *** [Makefile:14: javascript] Error 1
```
 
Log file:
```
40 http fetch GET 200 https://registry.npmjs.org/@types%2freact-redux 55ms (cache hit)
41 timing idealTree Completed in 1693ms
42 timing command:install Completed in 1738ms
43 verbose stack TypeError: Invalid Version: ^7.1.16
43 verbose stack     at new SemVer (/usr/local/lib/node_modules/npm/node_modules/semver/classes/semver.js:38:13)
43 verbose stack     at compare (/usr/local/lib/node_modules/npm/node_modules/semver/functions/compare.js:3:32)
43 verbose stack     at Object.gte (/usr/local/lib/node_modules/npm/node_modules/semver/functions/gte.js:2:30)
43 verbose stack     at CanPlaceDep.checkCanPlaceCurrent (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:173:51)
43 verbose stack     at CanPlaceDep.checkCanPlace (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:157:27)
43 verbose stack     at new CanPlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:114:26)
43 verbose stack     at PlaceDep.place (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:123:19)
43 verbose stack     at new PlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:31
43 verbose stack     at Array.map (<anonymous>)
```

**Comment by laemtl** [comment]
If you change all occurrences of
`"@types/react-redux": "^7.1.16"
`
for 
`"@types/react-redux": "^7.1.16" `

in the files above, does it help? If not, I will try to setup a VM with the same specs to try to reproduce.

**Comment by kefsaj** [comment]
Hey yes, it did help. Thank you! Made progress.

I was encountering 
``` 
lorisadmin@ubuntu-focal:/var/www/loris$ make
tools/gen-version.sh
npm install 
npm ERR! Invalid Version: ^17.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lorisadmin/.npm/_logs/2022-09-29T15_03_22_245Z-debug-0.log
make: *** [Makefile:14: javascript] Error 1
``` 
I temporarily removed this issue by removing "^" from all instances of ^17.0.1.

Trying to solve another snaggle at the moment.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-series-data-viewer@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0-0 || ^16.0.0-0" from @visx/group@1.17.1
npm ERR! node_modules/@visx/group
npm ERR!   @visx/group@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/lorisadmin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lorisadmin/.npm/_logs/2022-09-29T15_07_38_891Z-debug-0.log
npm ERR! code 1
npm ERR! path /var/www/loris
npm ERR! command failed
npm ERR! command sh -c -- cd modules/electrophysiology_browser/jsx/react-series-data-viewer && npm install

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lorisadmin/.npm/_logs/2022-09-29T15_06_08_988Z-debug-0.log
make: *** [Makefile:14: javascript] Error 1
```

afterwards when I tried to troubleshoot electrophysiology_browser/jsx/react-series-data-viewer, this is my situation I am in currently. 
```
> react-series-data-viewer@1.0.0 preinstall
> npm install --package-lock-only --legacy-peer-deps --force --ignore-scripts && npx npm-force-resolutions

npm WARN using --force I sure hope you know what you are doing.
npm ERR! Linux 5.4.0-126-generic
npm ERR! argv "/usr/local/bin/node" "/var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/node_modules/.bin/npm" "install" "--package-lock-only" "--legacy-peer-deps" "--force" "--ignore-scripts"
npm ERR! node v17.0.1
npm ERR! npm  v3.10.10

npm ERR! cb.apply is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/npm-debug.log
npm ERR! code 1
npm ERR! path /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer
npm ERR! command failed
npm ERR! command sh -c -- npm install --package-lock-only --legacy-peer-deps --force --ignore-scripts && npx npm-force-resolutions

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lorisadmin/.npm/_logs/2022-09-29T15_30_13_844Z-debug-0.log

```
Will keep you updated.
Thanks for your help!

**Comment by laemtl** [comment]
Let's do it the other way around. Can you share the content of your modules/electrophysiology_browser/jsx/react-series-data-viewer/package-lock.json?

**Comment by laemtl** [comment]
Since your npm is recent, there might be an easier way. 
Reset the changes made above in the main package.json:
`> git checkout package.json`

and replace the content of modules/electrophysiology_browser/jsx/react-series-data-viewer/package.json:

```
{
  "name": "react-series-data-viewer",
  "homepage": "https://github.com/aces/react-series-data-viewer/",
  "version": "1.0.0",
  "description": "react-series-data-viewer React component",
  "dependencies": {
    "@visx/axis": "^1.4.0",
    "@visx/group": "^1.0.0",
    "@visx/responsive": "^1.3.0",
    "@visx/shape": "^1.4.0",
    "d3-3d": "0.0.10",
    "d3-array": "^1.2.4",
    "d3-dsv": "^1.0.10",
    "d3-scale": "^2.1.2",
    "d3-scale-chromatic": "^1.3.3",
    "differenceequationsignal1d": "^0.1.1",
    "gl-matrix": "^2.8.1",
    "google-protobuf": "^3.6.1",
    "ramda": "^0.25.0",
    "react": "^16.12.0",
    "react-compound-slider": "^3.3.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.1",
    "redux": "^4.0.0",
    "redux-actions": "^2.6.1",
    "redux-logger": "^3.0.6",
    "redux-observable": "^1.0.0",
    "redux-thunk": "^2.3.0",
    "resize-observer-polyfill": "^1.5.0",
    "rxjs": "^6.6.3",
    "tslib": "^1.9.3"
  },
  "devDependencies": {
    "@types/react": "^16.12.0",
    "@types/react-dom": "^16.9.9",
    "@types/react-redux": "7.1.16"
  },
  "overrides": {
    "@types/react": "^16.12.0"
  },
  "license": "MIT",
  "repository": "https://github.com/aces/react-series-data-viewer"
}
```

**Comment by kefsaj** [comment]
> Since your npm version is recent, there might be an easier way. Reset the changes made above in the main package.json: `> git checkout package.json`
> 
> and replace the content of modules/electrophysiology_browser/jsx/react-series-data-viewer/package.json:
> 
> ```
> {
>   "name": "react-series-data-viewer",
>   "homepage": "https://github.com/aces/react-series-data-viewer/",
>   "version": "1.0.0",
>   "description": "react-series-data-viewer React component",
>   "dependencies": {
>     "@visx/axis": "^1.4.0",
>     "@visx/group": "^1.0.0",
>     "@visx/responsive": "^1.3.0",
>     "@visx/shape": "^1.4.0",
>     "d3-3d": "0.0.10",
>     "d3-array": "^1.2.4",
>     "d3-dsv": "^1.0.10",
>     "d3-scale": "^2.1.2",
>     "d3-scale-chromatic": "^1.3.3",
>     "differenceequationsignal1d": "^0.1.1",
>     "gl-matrix": "^2.8.1",
>     "google-protobuf": "^3.6.1",
>     "ramda": "^0.25.0",
>     "react": "^16.12.0",
>     "react-compound-slider": "^3.3.1",
>     "react-dom": "^16.13.1",
>     "react-redux": "^7.2.1",
>     "redux": "^4.0.0",
>     "redux-actions": "^2.6.1",
>     "redux-logger": "^3.0.6",
>     "redux-observable": "^1.0.0",
>     "redux-thunk": "^2.3.0",
>     "resize-observer-polyfill": "^1.5.0",
>     "rxjs": "^6.6.3",
>     "tslib": "^1.9.3"
>   },
>   "devDependencies": {
>     "@types/react": "^16.12.0",
>     "@types/react-dom": "^16.9.9",
>     "@types/react-redux": "7.1.16"
>   },
>   "overrides": {
>     "@types/react": "^16.12.0"
>   },
>   "license": "MIT",
>   "repository": "https://github.com/aces/react-series-data-viewer"
> }
> ```
> 
> Run the following before running `make`:
> 
> ```
> rm -R /var/www/loris/node_modules/
> rm /var/www/loris/package-lock.json
> rm -R /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/node_modules/
> rm /var/www/loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/package-lock.json
> ```

This is the result: 
``` Error - Can't read config.xml file. Webpack mode set to production.
Error: EACCES: permission denied, open '/var/www/loris/modules/mri_violations/js/columnFormatter.js'
make: *** [Makefile:15: javascript] Error 1```

**Comment by kefsaj** [comment]
Update on the situation:
    WARNING in ./node_modules/swagger-ui-dist/swagger-ui-bundle.js 2:993499
    Module parse failed: Unexpected token (2:993499)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    (Source code omitted for this binary file)
composer install --no-dev
> mkdir -p project/libraries
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - laminas/laminas-diactoros is locked to version 2.5.0 and an update of this package was not requested.
    - laminas/laminas-diactoros 2.5.0 requires php ^7.3 || ~8.0.0 -> your php version (8.1.11) does not satisfy that requirement.

make: *** [Makefile:4: all] Error 2
lorisadmin@ubuntu-focal:/var/www/loris$

**Comment by driusan** [comment]
hi @kefsaj,

LORIS 24 requires PHP 7.4 or PHP 8.0. PHP 8.1 support is added in LORIS 24.1 (which isn't quite released yet, but should be shortly..) Is it possible for you to downgrade to PHP 8.0.x?

**Comment by laemtl** [comment]
Good news, it seems like your are passing successfully the JS compilation now.

**Comment by kefsaj** [comment]
> hi @kefsaj,
> 
> LORIS 24 requires PHP 7.4 or PHP 8.0. PHP 8.1 support is added in LORIS 24.1 (which isn't quite released yet, but should be shortly..) Is it possible for you to downgrade to PHP 8.0.x?

Yes, working on that right now. 
Thanks!

**Comment by kefsaj** [comment]
> @kefsaj Good news, it seems like your are passing successfully the JS compilation now.

Yes, thank you guys for all your help!
Really appreciate all your help!!

**Comment by kefsaj** [comment]
Thank you so much for all the help!
Make ran successfully and have made really good progress with the install.
