### ISSUE TITLE
[imaging uploader] error 500 when uploading file bigger than 1 GB

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#8707]
**Describe the bug**

**==> EDIT: find out my VM has no space left. This issue might be linked to that.**

When uploading a compressed file that is more than 1 GB uncompressed in `.tar.gz` format, a 500 error is generated as such:

![Screenshot_2023-05-14_20-43-33](https://github.com/aces/Loris/assets/25327259/635d0121-15af-4424-a214-4437fad46a72)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to menu > imaging > imaging uploader
2. Go to upload tab
3. Fill out as `Phantom scan = no` and try uploading a folder bigger than is larger than 1 GB when uncompressed

The backend access gives this error in the logs:

```bash
[php:error] [pid 24198] [client ::1:40792] PHP Fatal error:  Uncaught ValueError: mime_content_type(): Argument #1 ($filename) cannot be empty in /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc:644
Stack trace:
#0 /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc(644): mime_content_type()
#1 /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc(296): LORIS\\imaging_uploader\\Imaging_Uploader->isCompressed()
#2 /var/www/Loris/php/libraries/File_Upload.class.inc(220): LORIS\\imaging_uploader\\Imaging_Uploader->isValid()
#3 /var/www/Loris/php/libraries/File_Upload.class.inc(110): File_Upload->callFileHandler()
#4 /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc(252): File_Upload->processFiles()
#5 /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc(149): LORIS\\imaging_uploader\\Imaging_Uploader->_saveFile()
#6 /var/www/Loris/php/libraries/NDB_Menu_Filter_Form.class.inc(82): LORIS\\imaging_uploader\\Imaging_Uploader->_process()
#7 /var/www/Loris/php/libraries/LorisForm.class.inc(1453): NDB_Menu_Filter_Form->_save()
#8 /var/www/Loris/php/libraries/NDB_Menu_Filter_Form.class.inc(50): LorisForm->process()
#9 /var/www/Loris/php/libraries/NDB_Menu_Filter_Form.class.inc(110): NDB_Menu_Filter_Form->save()
#10 /var/www/Loris/src/Middleware/UserPageDecorationMiddleware.php(239): NDB_Menu_Filter_Form->handle()
#11 /var/www/Loris/src/Middleware/PageDecorationMiddleware.php(58): LORIS\\Middleware\\UserPageDecorationMiddleware->process()
#12 /var/www/Loris/php/libraries/NDB_Page.class.inc(725): LORIS\\Middleware\\PageDecorationMiddleware->process()
#13 /var/www/Loris/php/libraries/Module.class.inc(328): NDB_Page->process()
#14 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): Module->handle()
#15 /var/www/Loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()
#16 /var/www/Loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()
#17 /var/www/Loris/src/Middleware/ExceptionHandlingMiddleware.php(54): LORIS\\Router\\ModuleRouter->handle()
#18 /var/www/Loris/src/Router/BaseRouter.php(132): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()
#19 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()
#20 /var/www/Loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()
#21 /var/www/Loris/htdocs/index.php(55): LORIS\\Middleware\\ContentLength->process()
#22 {main}
  thrown in /var/www/Loris/modules/imaging_uploader/php/imaging_uploader.class.inc on line 644, referer: http://localhost:8080/imaging_uploader/
```

Should probably be [tested here](https://github.com/aces/Loris/blob/25.0-release/modules/electrophysiology_uploader/php/upload.class.inc#L126)

**What did you expect to happen?**

If that is linked to the file size, a clear message for the user to say that the file is too big to process.

**Comment by regisoc** [comment]
@driusan cannot reproduce, seems the space was the issue.
