### ISSUE TITLE
[cbig][instruments] Saving PHP instrument return 500 error.

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#9234]
**Describe the bug**

Filling some instrument gives a 500 error.

Candid: `213004`

https://cbigr-test.loris.ca/instrument_list/?candID=213004&sessionID=13618

Link to the instrument:
https://cbigr-test.loris.ca/instruments/FamilyHistoryGeneticTestingForm/?commentID=213004CALS0000001136182721714682146&sessionID=13618&candID=213004

Log
```
[Thu May 02 16:41:01.021492 2024] [php:notice] [pid 5307] [client 192.168.122.1:54022] [CRITICAL] /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc:225: Uncaught TypeError: NDB_BVL_Instrument::factory(): Argument #1 ($loris) must be of type LORIS\\LORISInstance, null given, called in /var/www/loris/project/instruments/NDB_BVL_Instrument_FamilyHistoryGeneticTestingForm.class.inc on line 561 and defined in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc:225\nStack trace:\n#0 /var/www/loris/project/instruments/NDB_BVL_Instrument_FamilyHistoryGeneticTestingForm.class.inc(561): NDB_BVL_Instrument::factory()\n#1 /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc(563): NDB_BVL_Instrument_FamilyHistoryGeneticTestingForm->score()\n#2 /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc(3100): NDB_BVL_Instrument->save()\n#3 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(247): NDB_BVL_Instrument->handle()\n#4 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(58): LORIS\\Middleware\\UserPageDecorationMiddleware->process()\n#5 /var/www/loris/php/libraries/NDB_Page.class.inc(725): LORIS\\Middleware\\PageDecorationMiddleware->process()\n#6 /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc(3063): NDB_Page->process()\n#7 /var/www/loris/modules/instruments/php/module.class.inc(96): NDB_BVL_Instrument->process()\n#8 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\instruments\\Module->handle()\n#9 /var/www/loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()\n#10 /var/www/loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()\n#11 /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php(54): LORIS\\Router\\ModuleRouter->handle()\n#12 /var/www/loris/src/Router/BaseRouter.php(132): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#13 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#14 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#15 /var/www/loris/htdocs/index.php(73): LORIS\\Middleware\\ContentLength->process()\n#16 {main}\n  thrown, referer: https://cbigr-test.loris.ca/instruments/FamilyHistoryGeneticTestingForm/?commentID=213004CALS0000001136182721714682146&sessionID=13618&candID=213004
``` 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to this link https://cbigr-test.loris.ca/instruments/FamilyHistoryGeneticTestingForm/?commentID=213004CALS0000001136182721714682146&sessionID=13618&candID=213004
2. Click on `save values` at the end of the form
3. See 500 error

**Comment by ridz1208** [comment]
@regisoc should be fixed now
